name: Docker Build Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Sed
      run: sed -i "s|VERSION_TO_CHANGE|$(cat VERSION)|" Dockerfile
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/otlet/wp-redis:$(cat VERSION)
    - name: Log into registry ${{ env.REGISTRY }}
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish
      run: docker push ghcr.io/otlet/wp-redis:$(cat VERSION)
